### ISSUE TITLE
Handle Yoda Translate API errors gracefully

### ISSUE THREAD

**Issue by brucruz** [danielpantu/yodaTranslate#1]
If we are aware of possible errors that Yoda Translate API can throw, we can handle each one of them differently so we can return the user a more descriptive error message to the user. I'm pretty sure I got no response in one or two tries, even though I was not seen anything on the screen. As I was on mobile, I didn't check the console for logs.

https://github.com/danielpantu/yodaTranslate/blob/337dbb3077ed4feae5e3b3129a7a00c3bddf2a4f/script.js#L12

**Comment by danielpantu** [comment]
Done! Now the error messages from the API are displayed inside the Translation Output Area. Check the commit below:
47e6e3599e10e4f0f791313ef4e7960c20f10b0b
Thank you for contributing!
